<script lang="ts">
import Picker from './Picker.svelte';
import ExternalLinkIcon from './ExternalLinkIcon.svelte';
import {Button} from '@mutsuna/ui/button';
import {Input} from '@mutsuna/ui/input';
import * as Dialog from '@mutsuna/ui/responsive-dialog';
import {validSidebarLinks,reorderSidebarLink,type SidebarLink} from '../lib/sidebar-links';
import * as Sidebar from '@mutsuna/ui/sidebar';
import {SidebarUserMenu,SidebarWorkspaceSwitcher} from '@mutsuna/ui/sidebar-identity';
import {GraduationCap,CalendarDays,Clock3,Users,Settings2,History,ClipboardCheck,LogOut,UserRound,Plus,Pencil,MessageCircle,MessageSquareText,Puzzle} from '@lucide/svelte';
let {offline=false,roomAdmin=false,links=[],onLinks,value,room,rooms,role='admin',userName,userEmail,userAvatarUrl,onchange,onRoom,onLogout}:{offline?:boolean;roomAdmin?:boolean;links?:SidebarLink[];onLinks:(links:SidebarLink[])=>void;value:string;room:string;rooms:string[];role?:'admin'|'staff';userName:string;userEmail:string;userAvatarUrl?:string;onchange:(v:string)=>void;onRoom:(v:string)=>void;onLogout:()=>void}=$props();
const sidebar=Sidebar.useSidebar();
let open=$state(false),id=$state(''),label=$state(''),url=$state(''),scope=$state('all'),iconUrl=$state(''),detecting=$state(false),iconMessage=$state(''),position=$state('0'),error=$state('');
const safeLinks=$derived(links.filter(link=>validSidebarLinks([link])&&(!link.room||link.room===room)));
const orderLinks=$derived(roomAdmin?safeLinks.filter(link=>link.room===room):safeLinks);
function editLink(link?:SidebarLink){if(role!=='admin'||(roomAdmin&&link&&!link.room))return;id=link?.id||'';label=link?.label||'';url=link?.url||'';iconUrl=link?.iconUrl||'';iconMessage='';scope=roomAdmin||link?.room?'room':'all';position=String(link?orderLinks.findIndex(item=>item.id===link.id):orderLinks.length);error='';open=true}
function submit(){if(role!=='admin')return;const link={id:id||crypto.randomUUID(),label:label.trim(),url:url.trim(),...(iconUrl.trim()?{iconUrl:iconUrl.trim()}:{}),...(scope==='room'?{room}:{})};const next=id?links.map(item=>item.id===id?link:item):[...links,link];if(!validSidebarLinks(next)){error='表示名（80文字以内）と http:// または https:// から始まるURLを入力してください。リンクは30件までです。';return}if(roomAdmin){const scoped=next.filter(item=>item.room===room),ordered=reorderSidebarLink(scoped,room,link.id,Number(position));let index=0;onLinks(next.map(item=>item.room===room?ordered[index++]:item))}else onLinks(reorderSidebarLink(next,room,link.id,Number(position)));open=false}
async function detect(){if(role!=='admin'||detecting)return;detecting=true;iconMessage='';const requested=url.trim();try{const response=await fetch('/api/link-icon',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:requested,room})}),result=await response.json();if(url.trim()!==requested)return;if(!response.ok)throw Error(result.error);if(result.icons?.length){iconUrl=result.icons[0];iconMessage='ページ指定のアイコンを取得しました。'}else iconMessage='自動検出できませんでした。画像URLを指定するか、空欄のままにしてください。'}catch(e){iconMessage=(e as Error).message||'取得できませんでした。'}finally{detecting=false}}
function remove(){if(role!=='admin'||!id)return;onLinks(links.filter(link=>link.id!==id));open=false}

const items=[{value:'schedule',label:'授業スケジュール',icon:CalendarDays},{value:'placement',label:'月の配置確認',icon:ClipboardCheck},{value:'shifts',label:'シフト希望',icon:Clock3},{value:'attendance',label:'勤怠',icon:ClipboardCheck},{value:'messages',label:'メッセージ',icon:MessageCircle},{value:'students',label:'生徒一覧',icon:Users},{value:'imports',label:'生徒取り込み',icon:ClipboardCheck},{value:'teachers',label:'スタッフ',icon:GraduationCap},{value:'settings',label:'設定',icon:Settings2},{value:'history',label:'変更履歴',icon:History},{value:'feedback',label:'フィードバック',icon:MessageSquareText}];
const visibleItems=$derived(role==='staff'?items.filter(item=>item.value==='schedule'||item.value==='shifts'):items.filter(item=>!['attendance','messages','imports','feedback'].includes(item.value)));
function select(v:string){onchange(v);if(sidebar.isMobile)sidebar.setOpenMobile(false)}
function selectRoom(v:string){onRoom(v);if(sidebar.isMobile)sidebar.setOpenMobile(false)}
function openExtensionGuide(){if(sidebar.isMobile)sidebar.setOpenMobile(false);window.alert('ローカル検証では拡張機能を使用しません')}
function logout(){if(sidebar.isMobile)sidebar.setOpenMobile(false);onLogout()}
</script>
<Sidebar.Root collapsible="icon" hideHeaderSeam>
<Sidebar.Header class="h-14 shrink-0 justify-center">
  <SidebarWorkspaceSwitcher activeWorkspaceId={offline?'offline':room} activeDescription={offline?'オフライン':'ナレスク'} menuLabel={offline?'接続後に教室を確認します':'校舎を切り替え'} onSelectWorkspace={offline?()=>{}:selectRoom} workspaces={offline?[{id:'offline',name:'ナレスク',description:'接続後に教室を確認します'}]:rooms.map(id=>({id,name:id,description:'授業・シフト管理'}))}/>
</Sidebar.Header>
<Sidebar.Content><Sidebar.Group><Sidebar.GroupLabel>{offline?'メニュー':role==='staff'?'スタッフメニュー':'教室運営'}</Sidebar.GroupLabel>{#if role==='admin'&&!offline}<Sidebar.GroupAction aria-label="外部リンクを追加" title="外部リンクを追加" onclick={()=>editLink()}><Plus/></Sidebar.GroupAction>{/if}<Sidebar.GroupContent><Sidebar.Menu>{#each visibleItems as item (item.value)}<Sidebar.MenuItem><Sidebar.MenuButton isActive={value===item.value} onclick={()=>select(item.value)} tooltipContent={item.label} aria-current={value===item.value?'page':undefined}><item.icon/><span>{item.label}</span></Sidebar.MenuButton></Sidebar.MenuItem>{/each}{#each safeLinks as link (link.id)}<Sidebar.MenuItem><Sidebar.MenuButton tooltipContent={link.label}>{#snippet child({props})}<a {...props} href={link.url} target="_blank" rel="noopener noreferrer">{#key link.url+link.iconUrl}<ExternalLinkIcon url={link.url} iconUrl={link.iconUrl}/>{/key}<span>{link.label}</span></a>{/snippet}</Sidebar.MenuButton>{#if role==='admin'}{#if !roomAdmin||link.room}<Sidebar.MenuAction aria-label={`${link.label}を編集`} onclick={()=>editLink(link)}><Pencil/></Sidebar.MenuAction>{/if}{/if}</Sidebar.MenuItem>{/each}</Sidebar.Menu></Sidebar.GroupContent></Sidebar.Group></Sidebar.Content>
<Sidebar.Footer><SidebarUserMenu user={offline?{name:'オフライン',email:'接続後にアカウントを確認します'}:{name:userName,email:userEmail,avatarUrl:userAvatarUrl}} primaryItems={!offline&&role==='staff'?[{id:'account',label:'アカウント',icon:UserRound,onSelect:()=>select('account')},{id:'extension-guide',label:'拡張機能をインストール',icon:Puzzle,onSelect:openExtensionGuide}]:[]} secondaryItems={offline?[]:[{id:'logout',label:'ログアウト',icon:LogOut,onSelect:logout}]}/></Sidebar.Footer><Sidebar.Rail hideHeaderSeam/>
</Sidebar.Root>

{#if role==='admin'}<Dialog.Root bind:open><Dialog.Content><Dialog.Header><Dialog.Title>{id?'外部リンクを編集':'外部リンクを追加'}</Dialog.Title><Dialog.Description>表示範囲を選べます。スタッフも表示対象のリンクを開けます。</Dialog.Description></Dialog.Header><Dialog.Body><div class="link-fields"><div>表示範囲<Picker label="外部リンクの表示範囲" bind:value={scope} items={[...(!roomAdmin?[{value:'all',label:'全教室に表示'}]:[]),...(room?[{value:'room',label:`この教室だけ（${room}）`}]:[])]}/></div><div>表示順<Picker label="外部リンクの表示順" bind:value={position} items={Array.from({length:orderLinks.length+(id?0:1)},(_,index)=>({value:String(index),label:`${index+1}番目`}))}/><p>この教室で表示される外部リンクの並び順です。全教室リンク同士の順序は他の教室にも反映されます。</p></div><label>表示名<Input bind:value={label} maxlength={80} placeholder="例：教室の共有資料"/></label><label>リンク先<Input bind:value={url} type="url" maxlength={2048} placeholder="https://example.com"/></label><label>アイコン画像のURL（任意）<Input bind:value={iconUrl} type="url" maxlength={2048} placeholder="https://example.com/icon.png"/></label><Button variant="outline" disabled={!url.trim()||detecting} loading={detecting} onclick={detect}>リンク先からアイコンを自動取得</Button>{#if iconMessage}<p role="status">{iconMessage}</p>{/if}<details><summary>アイコン画像URLの取得方法</summary><ol><li>リンク先を別タブで開き、ロゴなどの画像を右クリックします。</li><li>「画像アドレスをコピー」、または「画像を新しいタブで開く」を選び、そのURLをコピーします。</li><li>上の欄へ貼り付けます。ページのURLではなく、画像だけが表示されるURLを指定してください。</li></ol><p>タブの小さなアイコンは直接コピーできない場合があります。まず自動取得を試してください。ログイン不要で開けるHTTP/HTTPSの画像URLを使います。端末内のファイルや期限付きURLは使わないでください。空欄なら標準のファビコンを試し、表示できない場合は外部リンクアイコンに戻ります。</p></details>{#if error}<p role="alert">{error}</p>{/if}<p>反映後、右上の「変更を保存」で確定します。</p></div></Dialog.Body><Dialog.Footer>{#if id}<Button variant="destructive" onclick={remove}>削除</Button>{/if}<Button variant="outline" onclick={()=>open=false}>キャンセル</Button><Button onclick={submit}>反映</Button></Dialog.Footer></Dialog.Content></Dialog.Root>{/if}
<style>.link-fields{display:grid;gap:16px}.link-fields label{display:grid;gap:6px}.link-fields p{font-size:13px;color:var(--muted-foreground)}</style>
