<script lang="ts">
import {AdminPanel} from '@mutsuna/ui/admin-layout';
import {Button} from '@mutsuna/ui/button';
import {Checkbox} from '@mutsuna/ui/checkbox';
import {Input} from '@mutsuna/ui/input';
import * as Table from '@mutsuna/ui/table';
import * as Dialog from '@mutsuna/ui/responsive-dialog';
import * as Avatar from '@mutsuna/ui/avatar';
import {showErrorToast,showSuccessToast} from '@mutsuna/ui/sonner';
import {Plus,Search,Link2,Copy,RefreshCw,ShieldOff,ExternalLink} from '@lucide/svelte';
import Picker from './Picker.svelte';
import CalendarPicker from './CalendarPicker.svelte';
import PeriodPicker from './PeriodPicker.svelte';
import type {State,Student,Preference} from '../lib/scheduler';
import {saveStudent,validatePeriods,preferenceLabel} from '../lib/students';
let {state:s,room,onChange,initialName='',onOpened,onMessages}:{state:State;room:string;onChange:(s:State,text:string)=>void;initialName?:string;onOpened:()=>void;onMessages:(studentId:string)=>void}=$props();
let search=$state(''),edit=$state<Student|null>(null),patterns=$state<Preference[]>([]),editingList=$state(false);
let shareStudent=$state<Student|null>(null),shareUrl=$state(''),shareActive=$state(false),shareLoading=$state(false);
type LineLink={lineUserId:string;displayName:string;pictureUrl:string|null;createdAt:number;linkedStudents:{id:string;name:string}[]};
let lineLinks=$state<LineLink[]>([]),unlinkTarget=$state<LineLink|null>(null);
const reference=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'}).slice(0,7);
const labels:Record<string,string>={active:'有効',paused:'休会',withdrawn:'退会',outside:'有効期間外'};
const rooms=$derived(s.settings?.campuses||[...new Set([...s.slots.map(x=>x.room),...(s.students||[]).map(x=>x.room),room])]);
const rows=$derived((s.students||[]).filter(x=>x.room===room&&(`${x.name} ${x.course}`).includes(search)).sort((a,b)=>a.name.localeCompare(b.name,'ja')));
const progressLink=(st:Student)=>st.progressSheetUrl?.trim()||'';
function open(st?:Student){edit=st?structuredClone(st):{id:crypto.randomUUID(),name:'',room,course:'',ownsComputer:false,monthlyLessons:4,reviewed:true,periods:[{id:crypto.randomUUID(),status:'active',from:reference,until:''}]};edit.progressSheetUrl??='';edit.ownsComputer??=false;patterns=structuredClone((s.preferences||[]).filter(p=>p.studentId===edit!.id)).map(p=>({...p,weeks:p.weeks.filter(week=>week>=1&&week<=4)}))}
$effect(()=>{if(initialName){const st=s.students?.find(x=>x.name===initialName&&x.room===room);if(st)open(st);onOpened()}});
function addPattern(){patterns.push({id:crypto.randomUUID(),studentId:edit!.id,name:edit!.name,room:edit!.room,course:edit!.course,weekday:6,weeks:[1,2,3,4],start:'09:00',end:'10:30'})}
const summary=preferenceLabel;
function updateInline(st:Student,patch:Partial<Student>,label:string){const next={...st,...patch,ownsComputer:patch.ownsComputer??st.ownsComputer??false};const preferences=structuredClone((s.preferences||[]).filter(p=>p.studentId===st.id));onChange(saveStudent(s,next,preferences),`${st.name}さんの${label}を変更`)}
function updateName(st:Student,value:string){const name=value.trim();if(!name||name===st.name)return;if(s.students?.some(x=>x.id!==st.id&&x.name===name&&x.room===st.room)){showErrorToast('同じ教室に同名の生徒が登録されています');return}updateInline(st,{name},'氏名')}
function save(){if(!edit)return;const st=$state.snapshot(edit);st.name=st.name.trim();st.course=st.course.trim();st.progressSheetUrl=st.progressSheetUrl?.trim()||'';if(!st.name||!st.room||!st.course){showErrorToast('生徒名・所属教室・現在のカリキュラムを入力してください');return}if(st.progressSheetUrl&&!/^https:\/\//.test(st.progressSheetUrl)){showErrorToast('進捗シートURLは https:// から入力してください');return}if(st.monthlyLessons!==2&&st.monthlyLessons!==4){showErrorToast('月の契約回数を選択してください');return}if(st.birthDate&&!/^\d{4}-\d{2}-\d{2}$/.test(st.birthDate)){showErrorToast('生年月日を確認してください');return}if(s.students?.some(x=>x.id!==st.id&&x.name===st.name&&x.room===st.room)){showErrorToast('同じ教室に同名の生徒が登録されています');return}const error=validatePeriods(st.periods);if(error){showErrorToast(error);return}if(patterns.some(p=>!p.weeks.length||!Number.isInteger(p.weekday)||!p.start||!p.end||p.start>=p.end||(p.alternatives||[]).some(a=>!Number.isInteger(a.weekday)||a.weekday<0||a.weekday>6||!a.start||!a.end||a.start>=a.end))){showErrorToast('希望スケジュールの対象週・曜日・授業コマを確認してください');return}onChange(saveStudent(s,st,$state.snapshot(patterns)),st.name+'さんの生徒情報・希望スケジュール・在籍期間を登録');edit=null}
async function openShare(st:Student){shareStudent=st;shareUrl='';shareLoading=true;try{const [linkResponse,lineResponse]=await Promise.all([fetch('/api/student-links?studentId='+encodeURIComponent(st.id)),fetch('/api/line-links?studentId='+encodeURIComponent(st.id))]);const link=await linkResponse.json(),line=await lineResponse.json();if(!linkResponse.ok)throw Error(link.error);if(!lineResponse.ok)throw Error(line.error);shareActive=!!link.active;lineLinks=line.links||[]}catch(e){showErrorToast((e as Error).message||'リンクの状態を確認できませんでした')}finally{shareLoading=false}}
async function unlinkLine(){if(!shareStudent||!unlinkTarget)return;shareLoading=true;try{const lineUserId=unlinkTarget.lineUserId,r=await fetch('/api/line-links?studentId='+encodeURIComponent(shareStudent.id)+'&lineUserId='+encodeURIComponent(lineUserId),{method:'DELETE'}),j=await r.json();if(!r.ok)throw Error(j.error);lineLinks=lineLinks.filter(link=>link.lineUserId!==lineUserId);unlinkTarget=null;showSuccessToast('この生徒とのLINE連携を解除しました')}catch(e){showErrorToast((e as Error).message||'LINE連携を解除できませんでした')}finally{shareLoading=false}}
async function issueLink(){if(!shareStudent)return;shareLoading=true;try{const r=await fetch('/api/student-links',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({studentId:shareStudent.id})});const j=await r.json();if(!r.ok)throw Error(j.error);shareUrl=j.url;shareActive=true;showSuccessToast('新しい秘密リンクを発行しました')}catch(e){showErrorToast((e as Error).message||'リンクを発行できませんでした')}finally{shareLoading=false}}
async function revokeLink(){if(!shareStudent)return;shareLoading=true;try{const r=await fetch('/api/student-links?studentId='+encodeURIComponent(shareStudent.id),{method:'DELETE'});const j=await r.json();if(!r.ok)throw Error(j.error);shareUrl='';shareActive=false;showSuccessToast('秘密リンクを無効にしました')}catch(e){showErrorToast((e as Error).message||'リンクを無効にできませんでした')}finally{shareLoading=false}}
async function copyLink(){if(!shareUrl)return;await navigator.clipboard.writeText(shareUrl);showSuccessToast('秘密リンクをコピーしました')}
</script>
<AdminPanel title="生徒情報" description="希望スケジュールと在籍期間を登録し、毎月の授業予定の作成に使います。">
<div class="student-toolbar"><div class="app-inline"><Search size={17}/><Input aria-label="生徒を検索" placeholder="生徒名・カリキュラムで検索" bind:value={search}/></div><Button variant={editingList?'default':'outline'} aria-pressed={editingList} onclick={()=>editingList=!editingList}>{editingList?'編集を終了':'編集モード'}</Button><Button onclick={()=>open()}><Plus size={16}/>生徒を登録</Button></div>
<p class="footnote">{room} · {rows.length}人。既存予定から作成した生徒のカリキュラム・在籍期間は、編集画面で確認してください。</p>
<Table.Root><Table.Header><Table.Row>{#each ['生徒名','所属教室','現在のカリキュラム','契約','PC','希望スケジュール','在籍期間','操作'] as title}<Table.Head>{title}</Table.Head>{/each}</Table.Row></Table.Header><Table.Body>{#each rows as st}<Table.Row class={editingList?'editing-row':undefined}><Table.Cell>{#if editingList}<Input class="inline-name" value={st.name} aria-label={`${st.name}さんの氏名`} onblur={e=>updateName(st,e.currentTarget.value)} onkeydown={e=>{if(e.key==='Enter')e.currentTarget.blur()}}/>{:else}<strong>{st.name}</strong>{#if !st.reviewed}<small class="student-review">要確認</small>{/if}{/if}</Table.Cell><Table.Cell>{#if editingList}<Picker label={`${st.name}さんの所属教室`} value={st.room} onchange={room=>updateInline(st,{room},'所属教室')} items={rooms.map(value=>({value,label:value}))}/>{:else}{st.room}{/if}</Table.Cell><Table.Cell>{#if editingList}<Picker label={`${st.name}さんのカリキュラム`} value={st.course} onchange={course=>updateInline(st,{course},'カリキュラム')} items={(s.settings?.curricula||[]).map(value=>({value,label:value}))}/>{:else}{st.course}{/if}</Table.Cell><Table.Cell>{#if editingList}<Picker label={`${st.name}さんの契約回数`} value={String(st.monthlyLessons)} onchange={value=>updateInline(st,{monthlyLessons:Number(value) as 2|4},'契約回数')} items={[{value:'2',label:'月2回'},{value:'4',label:'月4回'}]}/>{:else}<strong>月{st.monthlyLessons}回</strong>{/if}</Table.Cell><Table.Cell>{#if editingList}<button class="pc-toggle" class:owned={st.ownsComputer} type="button" aria-label={`${st.name}さんのPC所持状況を${st.ownsComputer?'未所持':'所持'}に変更`} onclick={()=>updateInline(st,{ownsComputer:!st.ownsComputer},'PC所持状況')}>{st.ownsComputer?'所持':'未所持'}</button>{:else}{st.ownsComputer?'所持':'未所持'}{/if}</Table.Cell><Table.Cell class={editingList?'editable-detail':undefined} onclick={()=>editingList&&open(st)}>{#each (s.preferences||[]).filter(p=>p.studentId===st.id) as p}<div class="student-pattern">{summary(p)}</div>{:else}<span class="muted">未登録</span>{/each}</Table.Cell><Table.Cell class={editingList?'editable-detail':undefined} onclick={()=>editingList&&open(st)}>{#each st.periods as period}<small class="student-period">{labels[period.status]}：{period.from}{period.status==='withdrawn'?'末まで':`〜${period.until||'期限なし'}`}</small>{/each}</Table.Cell><Table.Cell><div class="student-actions"><Button size="sm" variant="outline" onclick={()=>open(st)}>編集</Button>{#if progressLink(st)}<Button size="sm" variant="ghost" href={progressLink(st)} target="_blank" rel="noopener noreferrer"><ExternalLink size={14}/>進捗シート</Button>{/if}<Button size="sm" variant="ghost" onclick={()=>onMessages(st.id)}>メッセージ</Button><Button size="sm" variant="ghost" onclick={()=>openShare(st)}><Link2 size={14}/>秘密リンク</Button></div></Table.Cell></Table.Row>{:else}<Table.Row><Table.Cell colspan={8}>該当する生徒はいません。生徒を登録するか、検索条件を変更してください。</Table.Cell></Table.Row>{/each}</Table.Body></Table.Root>
</AdminPanel>
<Dialog.Root bind:open={()=>!!edit,(v:boolean)=>{if(!v)edit=null}}><Dialog.Content class="student-dialog"><Dialog.Header><Dialog.Title>生徒情報・希望スケジュール</Dialog.Title><Dialog.Description>契約回数、通塾希望、月単位の在籍期間を登録します。</Dialog.Description></Dialog.Header>{#if edit}<Dialog.Body><div class="form-grid"><label>生徒名<Input bind:value={edit.name}/></label><label>生年月日<Input type="date" bind:value={edit.birthDate}/><small class="footnote">保護者のLINE初回連携に使用します。</small></label><div class="field">所属教室<Picker label="所属教室" bind:value={edit.room} items={rooms.map(r=>({value:r,label:r}))}/></div><div class="field">月の契約回数<Picker label="月の契約回数" value={String(edit.monthlyLessons)} onchange={v=>{if(edit)edit.monthlyLessons=Number(v) as 2|4}} items={[{value:'2',label:'月2回'},{value:'4',label:'月4回'}]}/></div><div class="field">PC所持状況<Picker label="PC所持状況" value={edit.ownsComputer?'owned':'not-owned'} onchange={v=>{if(edit)edit.ownsComputer=v==='owned'}} items={[{value:'owned',label:'所持'},{value:'not-owned',label:'未所持'}]}/></div><div class="field wide">現在のカリキュラム<Picker label="カリキュラム" bind:value={edit.course} items={(s.settings?.curricula||[]).map(value=>({value,label:value}))}/></div><label class="wide">進捗シートURL<Input type="url" placeholder="https://docs.google.com/spreadsheets/..." bind:value={edit.progressSheetUrl}/><small class="footnote">登録すると生徒一覧から直接開けます。空欄でリンクを削除します。</small></label></div>
<div class="student-section-heading"><h3>希望スケジュール</h3><Button size="sm" variant="outline" onclick={addPattern}>＋ 追加</Button></div>
{#each patterns as p,i (p.id)}<div class="student-editor-row"><div class="field">希望の優先度<Picker label="希望の優先度" value={String(p.priority||1)} onchange={value=>p.priority=Number(value)} items={Array.from({length:12},(_,index)=>({value:String(index+1),label:`第${index+1}希望`}))}/></div><p class="footnote">同順位も設定できます。別の候補日時にもこの優先度が適用されます。</p>{#if p.source}<p class="footnote">取込元：{p.source}</p>{/if}<div class="form-grid"><div class="field wide">対象週<div class="checks">{#each [1,2,3,4,5] as w}<label><Checkbox checked={p.weeks.includes(w)} onCheckedChange={v=>p.weeks=v?[...p.weeks,w].sort() : p.weeks.filter(x=>x!==w)}/>第{w}</label>{/each}</div></div><div class="field">曜日<Picker label="曜日" value={String(p.weekday)} onchange={v=>p.weekday=Number(v)} items={[{value:'1',label:'月曜日'},{value:'2',label:'火曜日'},{value:'3',label:'水曜日'},{value:'4',label:'木曜日'},{value:'5',label:'金曜日'},{value:'6',label:'土曜日'},{value:'0',label:'日曜日'}]}/></div><div class="field">授業コマ<PeriodPicker state={s} room={edit.room} weekday={p.weekday} start={p.start} end={p.end} onchange={(start,end)=>{p.start=start;p.end=end}}/></div></div>{#each p.alternatives||[] as alternative,ai}<div class="form-grid"><div class="field">候補の曜日<Picker label="候補の曜日" value={String(alternative.weekday)} onchange={v=>alternative.weekday=Number(v)} items={[{value:'1',label:'月曜日'},{value:'2',label:'火曜日'},{value:'3',label:'水曜日'},{value:'4',label:'木曜日'},{value:'5',label:'金曜日'},{value:'6',label:'土曜日'},{value:'0',label:'日曜日'}]}/></div><div class="field">候補のコマ<PeriodPicker state={s} room={edit.room} weekday={alternative.weekday} start={alternative.start} end={alternative.end} onchange={(start,end)=>{alternative.start=start;alternative.end=end}}/></div></div><Button size="sm" variant="ghost" onclick={()=>p.alternatives=p.alternatives?.filter((_,index)=>index!==ai)}>候補を削除</Button>{/each}<Button size="sm" variant="ghost" onclick={()=>p.alternatives=[...(p.alternatives||[]),{weekday:p.weekday,start:p.start,end:p.end}]}>別の候補日時を追加</Button><div class="panel-row"><p class="footnote">{summary(p)}</p><Button size="sm" variant="ghost" onclick={()=>patterns=patterns.filter((_,j)=>i!==j)}>希望を削除</Button></div></div>{:else}<p class="footnote">希望スケジュールは未登録です。「追加」で登録してください。</p>{/each}
<div class="student-section-heading"><h3>在籍ステータスと期間</h3><Button size="sm" variant="outline" onclick={()=>edit?.periods.push({id:crypto.randomUUID(),status:'paused',from:reference,until:reference})}>＋ 期間を追加</Button></div>
{#each edit.periods as p,i (p.id)}<div class="student-editor-row"><div class="form-grid"><div class="field">ステータス<Picker label="在籍ステータス" bind:value={p.status} items={['active','paused','withdrawn'].map(value=>({value,label:labels[value]}))}/></div><div class="field">{p.status==='withdrawn'?'退会月（この月末まで在籍）':'開始月'}<CalendarPicker mode="month" label={p.status==='withdrawn'?'退会月':'開始月'} bind:value={p.from}/></div>{#if p.status!=='withdrawn'}<div class="field">終了月（任意）<CalendarPicker mode="month" label="終了月を選択" clearable bind:value={p.until}/></div>{/if}</div><Button size="sm" variant="ghost" onclick={()=>{if(edit)edit.periods=edit.periods.filter((_,j)=>i!==j)}}>期間を削除</Button></div>{/each}
<p class="footnote">有効期間を指定しない場合は全期間が有効です。休会期間は授業を作成せず、終了翌月から再開します。退会月の翌月以降は作成しません。例：9〜12月の休会は1月から再開、10月で退会は11月から対象外です。</p><p class="footnote">登録済みの授業は保持します。期間と重なる授業はスケジュールの確認事項に表示されるため、必要に応じて欠席・振替を設定してください。</p>
</Dialog.Body><Dialog.Footer><Button variant="outline" onclick={()=>edit=null}>キャンセル</Button><Button onclick={save}>生徒情報を反映</Button></Dialog.Footer>{/if}</Dialog.Content></Dialog.Root>
<Dialog.Root bind:open={()=>!!shareStudent,(v:boolean)=>{if(!v){shareStudent=null;shareUrl='';unlinkTarget=null}}}><Dialog.Content><Dialog.Header><Dialog.Title>{shareStudent?.name}さんのアクセス設定</Dialog.Title><Dialog.Description>秘密リンクと、LINEから閲覧できる保護者を管理します。</Dialog.Description></Dialog.Header><Dialog.Body>{#if shareUrl}<div class="share-link"><Input value={shareUrl} readonly aria-label="発行した秘密リンク"/><Button onclick={copyLink}><Copy size={15}/>コピー</Button></div><p class="footnote">新しいリンクを発行すると、以前のリンクは直ちに使えなくなります。</p>{:else if shareLoading&&!lineLinks.length}<p class="footnote">アクセス設定を確認しています…</p>{:else if shareActive}<div class="share-status"><Link2 size={18}/><p><strong>有効な秘密リンクがあります</strong><span>安全上、発行済みリンクの文字列は再表示しません。</span></p></div>{:else}<div class="share-status"><ShieldOff size={18}/><p><strong>有効な秘密リンクはありません</strong><span>LINE連携済みの保護者は引き続き閲覧できます。</span></p></div>{/if}<div class="student-section-heading"><h3>連携中のLINE</h3><span class="footnote">{lineLinks.length}件</span></div>{#each lineLinks as link}<div class="line-link-row"><Avatar.Root>{#if link.pictureUrl}<Avatar.Image src={link.pictureUrl} alt=""/>{/if}<Avatar.Fallback>{link.displayName.slice(0,1)}</Avatar.Fallback></Avatar.Root><div><strong>{link.displayName}</strong><small>連携日：{new Date(link.createdAt*1000).toLocaleDateString('ja-JP')}</small><small>閲覧できる生徒：{link.linkedStudents.map(student=>student.name).join('・')}</small></div><Button size="sm" variant="outline" disabled={shareLoading} onclick={()=>unlinkTarget=link}>この生徒との連携を解除</Button></div>{:else}<p class="footnote">LINE連携はありません。</p>{/each}</Dialog.Body><Dialog.Footer>{#if shareActive}<Button variant="ghost" disabled={shareLoading} onclick={revokeLink}><ShieldOff size={15}/>秘密リンクを無効化</Button>{/if}<Button disabled={shareLoading} onclick={issueLink}>{#if shareActive}<RefreshCw size={15}/>秘密リンクを再発行{:else}<Link2 size={15}/>秘密リンクを発行{/if}</Button></Dialog.Footer></Dialog.Content></Dialog.Root>
<Dialog.Root bind:open={()=>!!unlinkTarget,(v:boolean)=>{if(!v)unlinkTarget=null}}><Dialog.Content><Dialog.Header><Dialog.Title>LINE連携を解除しますか？</Dialog.Title><Dialog.Description>「{unlinkTarget?.displayName}」と「{shareStudent?.name}さん」の組み合わせだけを解除します。</Dialog.Description></Dialog.Header><Dialog.Body><p class="footnote">このLINEアカウントに紐づく他の生徒との連携は維持されます。</p></Dialog.Body><Dialog.Footer><Button variant="outline" disabled={shareLoading} onclick={()=>unlinkTarget=null}>キャンセル</Button><Button variant="destructive" loading={shareLoading} onclick={unlinkLine}>この連携を解除</Button></Dialog.Footer></Dialog.Content></Dialog.Root>
